spring:
  application:
    name: UongGiaConstruction

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-d4b9rrkhg0os73eq0mlg-a.singapore-postgres.render.com:5432/uonggia_construction
    username: uonggia_construction_user
    password: UsO1ytftXPGrqFCSe2Mv7BN56v8BWE77

    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

jwt:
  valid-duration: 3600
  refreshable-duration: 172800
  signer-key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa